name: UHC
main: me.lowlauch.uhc.Main
version: 0.1-ALPHA
author: lowlauch
commands:
  startuhc:
    description: Teleportiert dich zur eingegebenen Welt
    usage:
  heal:
    description: Heilt einen Spieler
    usage:
  wannastart:
    description: Wenn der Spieler bereit ist
    usage:
  bc:
    description: Broadcast Message
    usage:
  enduhc:
    description: Beendet UHC
    usage:
  teleport:
    description: Teleportiert zu Welt
    usage:
  cZu7pxloq2v:
    description: Setzt die Koordinaten der Craftingrezepte und Teleportiert dich dort hin geiheimer Befehl uwu xd
    usage:
  autostartuhc:
    description: Teleportiert dich zur eingegebenen Welt
    usage:
  toggleautostart:
    description: Aktiviert oder Deaktiviert Autostart
    usage:
  remake:
    description: Macht das Spiel neu wenn die Welt scheiße ist
    usage: