world:
  lobby: world
  x: -252
  y: 135
  z: 267

protection:
  time: 600
  border: -600
  
teams:
  maxsize: 2
  enabled: true
  
starter:
  items: true
  item1: STONE_AXE
  item2: STONE_PICKAXE

secret:
  command: cZu7pxloq2v