name: UHC
main: me.lowlauch.uhc.Main
version: 0.1-ALPHA
author: lowlauch
commands:
  uhc:
    description: Der main UHC Befehl
    usage: 
    
  teleport:
    description: Teleportiert zu Welt
    usage:
    
  secret: 
    description: Setzt die Koordinaten der Craftingrezepte und Teleportiert dich dort hin geiheimer Befehl uwu xd
    usage:
    
  heal:
    description: Heal Befehl
    usage: 
    
  remake: 
    description: Macht das Spiel neu wenn die Welt scheiﬂe ist
    usage: 